import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  getCodexSkillPath,
  getCodexSkillStatus,
  installCodexSkill,
  removeCodexSkill,
} from '../src/agent/codexSkill';

describe('Codex skill integration', () => {
  let tempHome = '';
  const originalCodexHome = process.env.CODEX_HOME;

  beforeEach(() => {
    tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'blackboard-codex-skill-'));
    delete process.env.CODEX_HOME;
  });

  afterEach(() => {
    fs.rmSync(tempHome, { recursive: true, force: true });
    if (originalCodexHome === undefined) delete process.env.CODEX_HOME;
    else process.env.CODEX_HOME = originalCodexHome;
  });

  it('installs and removes only its managed skill', () => {
    const downloadDir = path.join(tempHome, 'Downloads');
    const installed = installCodexSkill(downloadDir, tempHome);
    const skillPath = getCodexSkillPath(tempHome);

    expect(installed).toEqual({ installed: true, path: skillPath, managed: true });
    expect(fs.readFileSync(path.join(skillPath, 'SKILL.md'), 'utf8')).toContain('Blackbox BlackboardChina course export');
    expect(fs.readFileSync(path.join(skillPath, 'agents', 'openai.yaml'), 'utf8')).toContain('allow_implicit_invocation: true');
    expect(getCodexSkillStatus(tempHome).installed).toBe(true);

    const removed = removeCodexSkill(tempHome);
    expect(removed).toEqual({ installed: false, path: skillPath, managed: false });
    expect(fs.existsSync(skillPath)).toBe(false);
  });

  it('does not overwrite an unrelated skill directory', () => {
    const skillPath = getCodexSkillPath(tempHome);
    fs.mkdirSync(skillPath, { recursive: true });
    fs.writeFileSync(path.join(skillPath, 'SKILL.md'), '# Existing skill\n', 'utf8');

    expect(() => installCodexSkill(path.join(tempHome, 'Downloads'), tempHome)).toThrow('already exists and is not managed');
    expect(fs.readFileSync(path.join(skillPath, 'SKILL.md'), 'utf8')).toBe('# Existing skill\n');
  });

  it('honors CODEX_HOME when the user has configured a custom Codex home', () => {
    const configuredHome = path.join(tempHome, 'codex-home');
    process.env.CODEX_HOME = configuredHome;

    const skillPath = getCodexSkillPath(tempHome);

    expect(skillPath).toBe(path.join(configuredHome, 'skills', 'blackbox'));
  });

  it('installs into the default Codex skills directory', () => {
    expect(getCodexSkillPath(tempHome)).toBe(path.join(tempHome, '.codex', 'skills', 'blackbox'));
  });

  it('repairs a managed install left in the legacy directory', () => {
    const legacyPath = path.join(tempHome, '.agents', 'skills', 'blackbox');
    fs.mkdirSync(legacyPath, { recursive: true });
    fs.writeFileSync(path.join(legacyPath, 'SKILL.md'), '<!-- Managed by Blackbox. Do not edit this file to remove the integration. -->\n', 'utf8');

    const installed = installCodexSkill(path.join(tempHome, 'Downloads'), tempHome);

    expect(installed.path).toBe(path.join(tempHome, '.codex', 'skills', 'blackbox'));
    expect(fs.existsSync(legacyPath)).toBe(false);
  });
});
