import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  getHarnessSkillPath,
  getHarnessSkillStatus,
  installHarnessSkill,
  removeHarnessSkill,
} from '../src/agent/harnessSkill';

describe('Universal harness skill integration', () => {
  let tempHome = '';

  beforeEach(() => {
    tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'blackbox-harness-skill-'));
  });

  afterEach(() => {
    fs.rmSync(tempHome, { recursive: true, force: true });
  });

  it('installs and removes only its managed universal skill', () => {
    const downloadDir = path.join(tempHome, 'Downloads');
    const installed = installHarnessSkill(downloadDir, tempHome);
    const skillPath = getHarnessSkillPath(tempHome);
    const skillMarkdown = fs.readFileSync(path.join(skillPath, 'SKILL.md'), 'utf8');

    expect(installed).toEqual({ installed: true, path: skillPath, managed: true });
    expect(skillPath).toBe(path.join(tempHome, '.agents', 'skills', 'blackbox'));
    expect(skillMarkdown).toMatch(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
    expect(skillMarkdown.indexOf('<!-- Managed by Blackbox')).toBeGreaterThan(
      skillMarkdown.indexOf('\n---\n', 4),
    );
    expect(skillMarkdown).toContain('name: blackbox');
    expect(skillMarkdown).toContain('BlackboardChina course-material downloader');
    expect(skillMarkdown).toContain('compatible coding harnesses');
    expect(skillMarkdown).not.toContain('.codex');
    expect(fs.existsSync(path.join(skillPath, 'agents'))).toBe(false);
    expect(getHarnessSkillStatus(tempHome).installed).toBe(true);

    const removed = removeHarnessSkill(tempHome);

    expect(removed).toEqual({ installed: false, path: skillPath, managed: false });
    expect(fs.existsSync(skillPath)).toBe(false);
  });

  it('does not overwrite an unrelated skill directory', () => {
    const skillPath = getHarnessSkillPath(tempHome);
    fs.mkdirSync(skillPath, { recursive: true });
    fs.writeFileSync(path.join(skillPath, 'SKILL.md'), '# Existing skill\n', 'utf8');

    expect(() => installHarnessSkill(path.join(tempHome, 'Downloads'), tempHome)).toThrow(
      'already exists and is not managed',
    );
    expect(fs.readFileSync(path.join(skillPath, 'SKILL.md'), 'utf8')).toBe('# Existing skill\n');
  });

  it('marks a legacy managed file for repair instead of reporting it as installed', () => {
    const skillPath = getHarnessSkillPath(tempHome);
    fs.mkdirSync(skillPath, { recursive: true });
    fs.writeFileSync(
      path.join(skillPath, 'SKILL.md'),
      '<!-- Managed by Blackbox. Do not edit this file to remove the integration. -->\n' +
        '---\n' +
        'name: blackbox\n' +
        'description: legacy\n' +
        '---\n',
      'utf8',
    );

    expect(getHarnessSkillStatus(tempHome)).toEqual({
      installed: false,
      path: skillPath,
      managed: true,
    });
    expect(installHarnessSkill(path.join(tempHome, 'Downloads'), tempHome)).toEqual({
      installed: true,
      path: skillPath,
      managed: true,
    });
  });

  it('repairs a skill whose managed marker was stripped by hand', () => {
    const skillPath = getHarnessSkillPath(tempHome);
    fs.mkdirSync(skillPath, { recursive: true });
    // Valid blackbox frontmatter but the marker line was removed: neither the
    // old install nor remove could touch this state.
    fs.writeFileSync(
      path.join(skillPath, 'SKILL.md'),
      '---\nname: blackbox\ndescription: Read the local BlackboardChina course export.\n---\n\n# Hand edited\n',
      'utf8',
    );

    expect(getHarnessSkillStatus(tempHome)).toEqual({
      installed: false,
      path: skillPath,
      managed: false,
    });
    // Install must overwrite it (repair) instead of deadlocking.
    expect(installHarnessSkill(path.join(tempHome, 'Downloads'), tempHome).installed).toBe(true);
    // And remove must be able to clean it up again.
    expect(removeHarnessSkill(tempHome).installed).toBe(false);
  });
});
